config/routes.rb
DoSomthIn::Application.routes.draw do

  devise_for :user

  root :to => 'issues#index'

  resources :application

  resources :issues do
    member do
      get 'upvote'
      get 'downvote'
    end
  end

  get 'user/dashboard' => 'users#dashboard', :as => :dashboard

  resources :comments

end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @issues }
    end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
    @issue = Issue.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/new
  # GET /issues/new.json
  def new
    @issue = Issue.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @issue }
    end
  end

  # GET /issues/1/edit
  def edit
    @issue = Issue.find(params[:id])
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(params[:issue])

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render json: @issue, status: :created, location: @issue }
      else
        format.html { render action: "new" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /issues/1/upvote
  def upvote
    
    issue = Issue.find(params[:id])
    user = current_user

    vote = Vote.where(user:user, issue:issue)

    if vote.nil?
      flash[:notice] = "You voted Yay for this issue!"
    else
      Vote.destroy(vote.id)
      flash[:notice] = "You changed your vote to Yay for this issue!"
    end

    Vote.create(user:user, issue:issue, vote_type:Vote::TYPES[:up_vote])

    redirect_to issues_path
  end

  # GET /issues/1/downvote
  def downvote
    
  end

  # PUT /issues/1
  # PUT /issues/1.json
  def update
    @issue = Issue.find(params[:id])

    respond_to do |format|
      if @issue.update_attributes(params[:issue])
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue = Issue.find(params[:id])
    @issue.destroy

    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :ok }
    end
  end
end

app/views/issues/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="navbar navbar-default">

      <div class="navbar-header navbar-brand"><%= link_to issues_path do %><span class="glyphicon glyphicon-chevron-left"></span> Back to Issues<% end %></div>

      <% if user_signed_in? %>
      	<div class="ui-group-buttons pull-right" id="vote-menu">
			<%= link_to upvote_issue_path, :class => 'btn btn-success btn-lg', :id => 'upvote-button', :issue_id => @issue.id do %><span class="glyphicon glyphicon-thumbs-up"></span> Yay<% end %>
			<div class="or or-lg"></div>
			<%= link_to downvote_issue_path, :class => 'btn btn-danger btn-lg', :id => 'downvote-button', :issue_id => @issue.id do %><span class="glyphicon glyphicon-thumbs-down"></span> Nay<% end %>
		</div>
	<% end %>

    </div>

  </div>
</div>

<br />


<div class="h2"><%= @issue.title%>
	<small class="issue-meta pull-right">By: <%= @issue.owner_name %> Posted: <%= @issue.created_at %></small>
</div>

<hr />

  <b>Description:</b>
  <%= @issue.description %>
</p>

<p>
  <b>Goal:</b>
  <%= @issue.goal %>
</p>

<p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>